# Generated by Django 5.1.7 on 2025-03-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('id', models.FloatField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
