# Generated by Django 5.1.7 on 2025-07-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=32.0, verbose_name='Lat')),
                ('lon', models.FloatField(default=64.0, verbose_name='Lon')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_id', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(default='Desconocida', max_length=100)),
                ('temperatura', models.FloatField(default=0)),
                ('uv', models.FloatField(default=0)),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('color_uv', models.CharField(default='yellow', max_length=20)),
            ],
        ),
    ]
