# Generated by Django 5.1.7 on 2025-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=32.0, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(default=64.0, verbose_name='Lon'),
        ),
    ]
