# Generated by Django 5.1.7 on 2025-04-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0003_medicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('rojo', 'Rojo'), ('amarillo', 'Amarillo'), ('verde', 'Verde'), ('azul', 'Azul'), ('naranja', 'Naranja'), ('morado', 'Morado')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
