# Generated by Django 5.1.7 on 2025-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0004_semaforo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semaforo',
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='medicion',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicion',
            name='longitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicion',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicion',
            name='ubicacion',
            field=models.CharField(default='Cordoba', max_length=100),
        ),
        migrations.AddField(
            model_name='medicion',
            name='uv',
            field=models.FloatField(default=0),
        ),
    ]
