# Generated by Django 5.1.7 on 2025-04-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0005_delete_semaforo_remove_medicion_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='longitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='temperatura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='uv',
            field=models.FloatField(),
        ),
    ]
