# Generated by Django 5.1.7 on 2025-04-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0006_alter_medicion_latitud_alter_medicion_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='longitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='ubicacion',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='uv',
            field=models.FloatField(default=0),
        ),
    ]
