# Generated by Django 5.1.7 on 2025-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0007_alter_medicion_latitud_alter_medicion_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='color_uv',
            field=models.CharField(default='yellow', max_length=20),
        ),
    ]
