# Generated by Django 5.1.7 on 2025-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0009_medicion_ubicacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='color_temperatura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
