# Generated by Django 5.1.7 on 2025-04-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0010_medicion_color_temperatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
