# Generated by Django 5.1.7 on 2025-04-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0011_alter_medicion_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
