# Generated by Django 5.1.7 on 2025-04-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0012_alter_medicion_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='color_temperatura',
        ),
    ]
